# Setup
name:                ThunderFIT
title:               ThunderFIT
tagline:             Fitness Made Simple
author:              BeeBack, LLC.
author_email:        sazzad@beeback.io
url:                 http://localhost:4000
baseurl:             ''
permalink:           pretty
exclude:             [README.markdown]
analytics_id:        "UA-104952515-1"

# SEO information
seo:
    description: "Something Here"
    keywords: "loyalty, rewards, ar, ai, suggestions, discovery, discover, find, cafe, cake, coffee, drinks, food"

# Owner/author information
owner:
    name:           ThunderFIT
    avatar:         logo.svg
    bio:            "Something here"
    email:          sazzad@beeback.io
    twitter:        thunderfitapp
    github:         iamshipon1988
    instagram:      thunderfitapp
    location:       "New York, NY"


# Custom vars
version:             1.5.0
github:
  repo:


# Plugins
plugins:
- jekyll-sitemap
- jekyll-seo-tag
